kind: Service
apiVersion: v1
metadata:
  name: nginxplus
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginxplus
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxplus-deployment
  labels:
    app: nginxplus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxplus
  template:
    metadata:
      labels:
        app: nginxplus
    spec:
      containers:
      - name: nginxplus
        image: codygreen/nginxplus
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
